### PR TITLE
updating simdjson to 3.9.5

### LINKED ISSUE #91: CRAN warnings with g++-14
Via email from CRAN:

<blockquote>

Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_RcppSimdJson.html>.

Please correct before 2024-08-03 to safely retain your package on CRAN.

This is primarily about the compiler C++ warnings
shown in the fedora-gcc results.  These are from g++ 14.x
which was released a couple of months ago.

The CRAN Team

</blockquote>

which shows both via https://cran.r-project.org/web/checks/check_results_RcppSimdJson.html directly and the 'gcc12' link

<blockquote>

* checking whether package ‘RcppSimdJson’ can be installed ... [241s/251s] WARNING
Found the following significant warnings:
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14229:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14230:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14232:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16393:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16394:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16396:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:20872:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:20873:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/Rc
ppSimdJson/deserialize/../../simdjson.h:20875:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/Type_Doctor.hpp:43:65: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14229:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14230:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14232:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16393:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16394:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16396:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20872:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20873:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20875:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
See ‘/data/gannet/ripley/R/packages/tests-devel/RcppSimdJson.Rcheck/00install.out’ for details.
* used C++ compiler: ‘g++-14 (GCC) 14.1.0’

</blockquote>

Any sage advice here @lemire ?  I guess I could hardwire C++17 as a standard in the short-term but I presume 'eventually' we need to make a change.

Now, it could well be that the change is already made upstream -- I have not sync'ed in a while.  If so just let me know....

Dirk (in Europe for a few more days)

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/eddelbuettel/rcppsimdjson/issues/91

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I don't remember from the top of my head whether I need manual mods  but I think I don't so in in goes!

**Comment by eddelbuettel** [comment]
Thanks again -- this is now on CRAN after an extra day it took for a manual / one-off check against the newer g++.

**Comment by eddelbuettel** [comment]
@lemire I spoke too soon. Other email from Dortmund says

<blockquote>

Thanks, we see:

Fedora-gcc 14:

Found the following significant warnings:
  ../inst/include/RcppSimdJson/deserialize/Type_Doctor.hpp:43:65: warning:
template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]

Please fix and resubmit.

</blockquote>

Can you take a look, time permitting, and suggest a change? I am currently fighting a different fire with Rcpp.

Update 1:  ~Worst case, as mentioned, I could enforce C++17, at least for now.~  Apparently we already compile as C++17 so that is not an option.

Update 2:  The fix may be reasonably simple.  At least I have something that passes muster under `g++-13`.

Update 3: Now on CRAN.

**Comment by lemire** [comment]
Is there anything that needs to be done? The warning should be gone.

**Comment by eddelbuettel** [comment]
It's all good, I 'merely' had to remove the offending template-id in one ctor declaration on the R 'glue' side of the package.

The updated package (with `simdjson` 3.9.5) now on CRAN.

**Pull request merged**
