### PR TITLE
Integer handling

### PR DESCRIPTION
**Pull request by knapply**
@eddelbuettel  @dcooley - Let's try this again. Addressing #13

If/when all seems well, I'll update `ChangeLog`, `NEWS` before merging.

### CODE REVIEW

**Review by dcooley — APPROVED** [review]

**Review by eddelbuettel — APPROVED** [review]
Looks good to me too; checked it out, made a package (under version 0.0.5.1) and tested it.

**Comment by eddelbuettel** [comment]
And as you said: you may as well add ChangeLog and NEWS entry.  As maintainer I sometimes tweak these a little so can I also add them -- but a first pass (which may even be final...) would be appreciated.

**Comment by knapply** [comment]
Feel free to tweak away!

**Comment by eddelbuettel** [comment]
We could have done the tweaking before the merge but six of one, half a dozen of the other.

But much smoother ride this time -- I'll just make a quick cleanup.

**Pull request merged**
