### PR TITLE
add raw vector support (plus docs, example, tests)

### PR DESCRIPTION
**Pull request by knapply**
Addresses https://github.com/eddelbuettel/rcppsimdjson/issues/35

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
You're fast.

Quick addition of a ChangeLog entry?

**Comment by knapply** [comment]
Just pushed. I added yesterday's as well.

**Comment by eddelbuettel** [comment]
Needed a small cleanup I just added.

**Comment by knapply** [comment]
> Needed a small cleanup I just added.

Thank you!

**Pull request merged**
